CREATE TABLE public.call (
    Call_ID VARCHAR PRIMARY KEY,
    Broker_Name VARCHAR,
    Lead_ID INT REFERENCES public.Lead(Lead_ID) NULL,
    Call_Type VARCHAR(255),
    Date_Time TIMESTAMP,
    Talk_Time INT,
    Outcome VARCHAR(255),
    Call_Segment VARCHAR(255),
    Inbound_Number VARCHAR(255),
    Prospect_Number VARCHAR(255)
);

CREATE TABLE public.staging_call (
    Call_ID VARCHAR PRIMARY KEY,
    Broker_Name VARCHAR,
    Lead_ID VARCHAR,
    Call_Type VARCHAR(255),
    Date_Time VARCHAR(255),
    Talk_Time VARCHAR(255),
    Outcome VARCHAR(255),
    Call_Segment VARCHAR(255),
    Inbound_Number VARCHAR(255),
    Prospect_Number VARCHAR(255)
);

CREATE TABLE public.Lead (
    Lead_ID INT PRIMARY KEY,
    Source VARCHAR,
    Lead_Status VARCHAR,
    Lead_Score VARCHAR,
    Stage_ID INT REFERENCES public.Stage(Stage_ID),
    Milestone VARCHAR,
    Broker_Name VARCHAR,
    "Group" VARCHAR,
    Date_Added TIMESTAMP,
    Last_Action VARCHAR,
    First_Contact_Attempt_Date TIMESTAMP,
    Action_Count INT,
    Total_Contact_Attempts INT,
    Last_Action_Date TIMESTAMP,
    First_Assignment_Distribution_Date TIMESTAMP,
    First_Assignment_Distribution_User VARCHAR,
    Lead_Source_Group VARCHAR,
    Creative VARCHAR,
    Broker VARCHAR,
    Opener VARCHAR,
    IRA_Investment_Dollar VARCHAR,
    Cash_Investment_Dollar VARCHAR,
    Deal_Type VARCHAR,
    Transfer_Type VARCHAR,
    "TO_Date" TIMESTAMP,
    SF_Lead_ID VARCHAR,
    Velocify_ID VARCHAR,
    Original_Broker VARCHAR,
    SF_Lead_Owner VARCHAR,
    Junior_Broker VARCHAR,
    Last_Activity TIMESTAMP,
    Intellect_Client_ID VARCHAR,
    Intellect_Broker VARCHAR,
    First_Name VARCHAR,
    Last_Name VARCHAR,
    Home_Phone VARCHAR,
    Work_Phone VARCHAR,
    Mobile_Phone VARCHAR,
    Email VARCHAR,
    Secondary_Email VARCHAR,
    Address VARCHAR,
    City VARCHAR,
    State VARCHAR,
    Zip_Postal_Code VARCHAR,
    Source_Code VARCHAR,
    SubID VARCHAR
);
CREATE TABLE public.Staging_Lead (
    Lead_ID VARCHAR PRIMARY KEY,
    Source VARCHAR,
    Lead_Status VARCHAR,
    Lead_Score VARCHAR,
    Stage_ID VARCHAR,
    Milestone VARCHAR,
    Broker_Name VARCHAR,
    "Group" VARCHAR,
    Date_Added VARCHAR,
    Last_Action VARCHAR,
    First_Contact_Attempt_Date VARCHAR,
    Action_Count VARCHAR,
    Total_Contact_Attempts VARCHAR,
    Last_Action_Date VARCHAR,
    First_Assignment_Distribution_Date VARCHAR,
    First_Assignment_Distribution_User VARCHAR,
    Lead_Source_Group VARCHAR,
    Creative VARCHAR,
    Broker VARCHAR,
    Opener VARCHAR,
    IRA_Investment_Dollar VARCHAR,
    Cash_Investment_Dollar VARCHAR,
    Deal_Type VARCHAR,
    Transfer_Type VARCHAR,
    "TO_Date" VARCHAR,
    SF_Lead_ID VARCHAR,
    Velocify_ID VARCHAR,
    Original_Broker VARCHAR,
    SF_Lead_Owner VARCHAR,
    Junior_Broker VARCHAR,
    Last_Activity VARCHAR,
    Intellect_Client_ID VARCHAR,
    Intellect_Broker VARCHAR,
    First_Name VARCHAR,
    Last_Name VARCHAR,
    Home_Phone VARCHAR,
    Work_Phone VARCHAR,
    Mobile_Phone VARCHAR,
    Email VARCHAR,
    Secondary_Email VARCHAR,
    Address VARCHAR,
    City VARCHAR,
    State VARCHAR,
    Zip_Postal_Code VARCHAR,
    Source_Code VARCHAR,
    SubID VARCHAR
);

CREATE TABLE public.Transcript (
    Transcript_ID VARCHAR PRIMARY KEY,
    Call_ID VARCHAR REFERENCES public.Call(Call_ID) NULL,
    Transcript_Url VARCHAR
);


CREATE TABLE public.Lead_Log ( 
    Lead_Log_Id VARCHAR PRIMARY KEY,
    Log_Type VARCHAR,
    Log_Actor VARCHAR,
    Log_Date TIMESTAMP,
    Log_Result VARCHAR,
    Log_Note VARCHAR,
    Log_Contact VARCHAR,
    Lead_ID INT REFERENCES public.Lead(Lead_ID) NULL,
    Campaign_Name VARCHAR,
    Affiliate_Name VARCHAR,
    Status VARCHAR,
    Last_Contact_Attempt_Date TIMESTAMP
);

CREATE TABLE public.staging_Lead_Log (
    Lead_Log_Id VARCHAR PRIMARY KEY,
    Log_Type VARCHAR,
    Log_Actor VARCHAR,
    Log_Date VARCHAR,
    Log_Result VARCHAR,
    Log_Note VARCHAR,
    Log_Contact VARCHAR,
    Lead_ID INT,
    Campaign_Name VARCHAR,
    Affiliate_Name VARCHAR,
    Status VARCHAR,
    Last_Contact_Attempt_Date VARCHAR
);


CREATE TABLE public.Broker (
    Broker_ID VARCHAR PRIMARY KEY,
    Broker_Name VARCHAR(255),
    phoneNumber VARCHAR(255),
    email VARCHAR(255),
    extension VARCHAR(255),
    state VARCHAR(255),
    role VARCHAR(255)
);
